sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5t7tTU2wTdDYiZ39USW5
    access-key-secret: lVEsvJDQZYfXbbxRYVyKZOaP8lP69J
    bucket-name: candice-bucket

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx76a20c840757c17d
    secret: b78723b2d105ded0f840ed3869c50521
